name: tglima_dart_framework
description: Small collection of helpers created for Dart
version: 3.5.20240827
homepage: https://tglima.github.io/

environment:
  sdk: '>=3.5.1 <3.5.9'

dependencies:
  encrypt: 5.0.3

dev_dependencies:
  lints: 4.0.0
  test: ^1.16.0
